name: Build LaTeX document
on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    env:
      DOC: ${{ github.event.repository.name }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Compile LaTeX document
        id: compileLaTeXdocument
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            main.tex
          working_directory: doc
          extra_system_packages: "git patch"
          latexmk_shell_escape: true
          pre_compile: git config --global --add safe.directory /github/workspace
        env:
          TEXINPUTS: ".:$PWD/../latex-styles-master/styles//:"
          BSTINPUTS: ".:$PWD/../latex-styles-master/styles/common"
          BIBINPUTS: ".:$PWD/../latex-styles-master/share"
        continue-on-error: true
      - name: Upload PDF
        if: steps.compileLaTeXdocument.outcome == 'success' && github.event_name != 'push'
        uses: actions/upload-artifact@v3
        with:
          name: Success--Here-is-the-PDF
          path: |
            doc/main.pdf
      - name: Upload build logs
        if: steps.compileLaTeXdocument.outcome == 'failure' && github.event_name != 'push'
        uses: actions/upload-artifact@v3
        with:
          name: Build-Failed--Here-are-the-Logs
          path: |
            doc/.aux/*.log
      - name: Fail job if build failed
        if: steps.compileLaTeXdocument.outcome == 'failure'
        run: exit 1